name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    if: ${{ github.repository_owner == 'cosmicds' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          VUE_APP_CDS_API_KEY: ${{ secrets.CDS_API_KEY }}

          # - name: BrowserStack env setup
          #   uses: browserstack/github-actions/setup-env@master
          #   with:
          #     username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          #     access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

          # - name: BrowserStack local tunnel setup
          #   uses: browserstack/github-actions/setup-local@master
          #   with:
          #     local-testing: start
          #     local-identifier: random

          # - name: Run BrowserStack tests
          #   run: |
          #     set -xeuo pipefail
          #     yarn serve &
          #     sleep 10
          #     yarn test-bslocal -e default,firefox,edge,safari -o reports

      - name: Check for draft flag
        uses: sergeysova/jq-action@v2
        id: draft
        with:
          cmd: cat package.json | jq -r '.draft // false'

      - name: Create folder for deployment
        run: |
          mkdir deployment
          mkdir deployment/dev

      - name: Move current build to deployment
        id: prepare
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          echo "Current branch: ${BRANCH}"
          [[ "$BRANCH" == "dev" ]] && folder="dev" || folder="."
          echo "Folder to use: ${folder}"
          mv dist/* deployment/${folder}
          [[ "$BRANCH" == "dev" ]] && other="main" || other="dev"
          echo "Other branch: ${other}"
          echo "other=${other}" >> "$GITHUB_OUTPUT"

      - name: Check out the other branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.prepare.outputs.other }}
          path: other

      - name: Build other branch and move to deployment
        env:
          BRANCH: ${{ steps.prepare.outputs.other }}
          VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          VUE_APP_CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
        run: |
          cd other
          yarn install
          yarn build
          [[ "$BRANCH" == "dev" ]] && folder="dev" || folder="."
          mv dist/* ../deployment/${folder}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ steps.draft.outputs.value }} == 'false'
        with:
          branch: gh-pages
          folder: deployment 
          ssh-key: ${{ secrets.DEPLOY_KEY }}
